noDecompress option added
feross/simple-get pull request #62
Opened 2020-07-24 19:58 UTC by zdm

`noDecompress` option allows to skip response body decompression.

2020-07-28 10:55 UTC, zdm commented
Hey.
In our project we need to get gzipped content without decompression. Is it possible to accept this PR or at least give the answer does it has any chances to be accepted? I need to know what to do next. Thank you.

2020-11-23 21:20 UTC, feross requested changes
Thanks for the PR! I'll accept it but can you make the requested changes?

2020-11-23 21:20 UTC, feross commented on README.md
> +  // Special option `noDecompress` allows to skip response body decompression.
Can you add a new section to the readme, similar to the others that already exist there, to document how to use this? This one line is insufficent.

2020-11-23 21:20 UTC, feross commented on index.js
> +    const tryUnzip = !opts.noDecompress && typeof decompressResponse === 'function' && opts.method !== 'HEAD'
Rename the option to `decompress` and change the check to `decompress === false`

2024-09-13 20:19 UTC, closed without merging